# docker-compose.yml

version: '3.8'
services:
  auth-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DATABASE_NAME=auth_db
      - SECRET_KEY=your-very-secure-secret-key
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
